'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Bookings

    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litSuccess As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents txtFromDate As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtToDate As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    Protected WithEvents pnlNoResults As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents rptBookings As Global.System.Web.UI.WebControls.Repeater

End Class
