'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin
    Partial Public Class Rooms

        Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel

        Protected WithEvents litSuccess As Global.System.Web.UI.WebControls.Literal

        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

        Protected WithEvents litAvailable As Global.System.Web.UI.WebControls.Literal

        Protected WithEvents litOccupied As Global.System.Web.UI.WebControls.Literal

        Protected WithEvents litCleaning As Global.System.Web.UI.WebControls.Literal

        Protected WithEvents litMaintenance As Global.System.Web.UI.WebControls.Literal

        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

        Protected WithEvents ddlFloor As Global.System.Web.UI.WebControls.DropDownList

        Protected WithEvents ddlRoomType As Global.System.Web.UI.WebControls.DropDownList

        Protected WithEvents rptRooms As Global.System.Web.UI.WebControls.Repeater

        Protected WithEvents pnlNoRooms As Global.System.Web.UI.WebControls.Panel

    End Class
End Namespace
