'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Login

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litSuccess As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents chkRememberMe As Global.System.Web.UI.WebControls.CheckBox

    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

End Class
