'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace HotelCore.Web
    Partial Public Class _Default

        Protected WithEvents txtCheckIn As Global.System.Web.UI.WebControls.TextBox

        Protected WithEvents txtCheckOut As Global.System.Web.UI.WebControls.TextBox

        Protected WithEvents ddlGuests As Global.System.Web.UI.WebControls.DropDownList

        Protected WithEvents btnCheckAvailability As Global.System.Web.UI.WebControls.Button

    End Class
End Namespace
