'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace HotelCore.Web

    Partial Public Class ErrorPage

        '''<summary>
        '''litErrorCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorCode As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litErrorTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorMessage As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
