'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Checkout

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents pnlAdditionalGuests As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents rptAdditionalGuests As Global.System.Web.UI.WebControls.Repeater

    Protected WithEvents txtSpecialRequests As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents ddlPaymentMethod As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents pnlCardDetails As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents txtCardNumber As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents ddlExpiryMonth As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents ddlExpiryYear As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents txtCVV As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents chkTerms As Global.System.Web.UI.WebControls.CheckBox

    Protected WithEvents btnCompleteBooking As Global.System.Web.UI.WebControls.Button

    Protected WithEvents litRoomType As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litRoomNumber As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litCheckIn As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litCheckOut As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litGuests As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litNights As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litDailyRate As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litSubtotal As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litTax As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litTotal As Global.System.Web.UI.WebControls.Literal

End Class
