'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace HotelCore.Web

    Partial Public Class SiteMaster

        Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        Protected WithEvents lnkLogout As Global.System.Web.UI.WebControls.LinkButton

        Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

        Protected WithEvents txtNewsletter As Global.System.Web.UI.WebControls.TextBox

        Protected WithEvents btnSubscribe As Global.System.Web.UI.WebControls.Button

        Protected WithEvents ScriptsPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
