CREATE TABLE [dbo].[DynamicPricingStrategies] (
    [StrategyID]               INT             IDENTITY (1, 1) NOT NULL,
    [StrategyName]             NVARCHAR (100)  NOT NULL,
    [StrategyType]             NVARCHAR (50)   NOT NULL,
    [Description]              NVARCHAR (500)  NULL,
    [Priority]                 INT             DEFAULT ((10)) NOT NULL,
    [IsActive]                 BIT             DEFAULT ((1)) NULL,
    [OccupancyThreshold]       DECIMAL (5, 2)  NULL,
    [OccupancyAdjustmentType]  NVARCHAR (20)   NULL,
    [OccupancyAdjustmentValue] DECIMAL (10, 2) NULL,
    [UrgencyDaysThreshold]     INT             NULL,
    [UrgencyAdjustmentType]    NVARCHAR (20)   NULL,
    [UrgencyAdjustmentValue]   DECIMAL (10, 2) NULL,
    [HolidayName]              NVARCHAR (100)  NULL,
    [HolidayStartDate]         DATE            NULL,
    [HolidayEndDate]           DATE            NULL,
    [HolidayAdjustmentType]    NVARCHAR (20)   NULL,
    [HolidayAdjustmentValue]   DECIMAL (10, 2) NULL,
    [DiscountCode]             NVARCHAR (50)   NULL,
    [DiscountStartDate]        DATE            NULL,
    [DiscountEndDate]          DATE            NULL,
    [DiscountAdjustmentType]   NVARCHAR (20)   NULL,
    [DiscountAdjustmentValue]  DECIMAL (10, 2) NULL,
    [DiscountMinimumStay]      INT             NULL,
    [DiscountBookingTimeStart] TIME (7)        NULL,
    [DiscountBookingTimeEnd]   TIME (7)        NULL,
    [CreatedBy]                INT             NULL,
    [CreatedDate]              DATETIME2 (7)   DEFAULT (getutcdate()) NULL,
    [ModifiedBy]               INT             NULL,
    [ModifiedDate]             DATETIME2 (7)   DEFAULT (getutcdate()) NULL,
    PRIMARY KEY CLUSTERED ([StrategyID] ASC),
    CONSTRAINT [CHK_Strategy_Type] CHECK ([StrategyType]='Base' OR [StrategyType]='Discount' OR [StrategyType]='Holiday' OR [StrategyType]='Urgency' OR [StrategyType]='Occupancy'),
    CONSTRAINT [FK_DynamicPricingStrategies_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([UserID]),
    CONSTRAINT [FK_DynamicPricingStrategies_ModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([UserID]),
    UNIQUE NONCLUSTERED ([StrategyName] ASC)
);

